#DEPENDENCIES COULD BE OUT OF DATE.

[package]
name = "user/rojotemplate"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
<<<<<<< HEAD
Roact = "roblox/roact@1.4.2"
Hooks = "kampfkarren/roact-hooks@0.5.0"
RoactFlipper = "reselim/roact-flipper@1.1.0"
Flipper = "reselim/flipper@2.0.0"
=======
Knit = "sleitnick/knit@^1.4"
Component = "sleitnick/component@2.4.6"
Signal = "sleitnick/signal@1.2.1"
Timer = "sleitnick/timer@1.1.2"
cmdr = "evaera/cmdr@1.9.0"
Roact = "core-packages/roact-compat@17.0.1-rc.16.1"
>>>>>>> 403f7cbe5378d968fa167a2b66ac2dd691b9c505
